obj-$(CONFIG_ARMADILLO_WLAN_AWL13_USB)	+= awl13_log.o awl13_usbdrv.o \
					   awl13_ioctl.o awl13_fw.o \
					   awl13_sysfs.o awl13_wid.o
obj-$(CONFIG_ARMADILLO_WLAN_AWL13_SDIO) += awl13_log.o awl13_sdiodrv.o \
					   awl13_ioctl.o awl13_fw.o \
					   awl13_sysfs.o awl13_wid.o
obj-$(CONFIG_ARMADILLO_WLAN_AWL13_WMM)	+= awl13_wmm.o
